STACK_NAME=ChatStack
echo stack name is $STACK_NAME
# echo $KMS_KEY

aws cloudformation deploy --template-file ./sqs-cloudformation.yaml --stack-name $STACK_NAME
#  --kms-key-id $KMS_KEY
# Uncomment KMS related lines and add the kms-key-id paramenter to the command if you want to encrypt the S3 files generated by cloudformation.
